image: alpine:latest

build_gcc:
  stage: build
  before_script:
    - apk add --no-cache g++ make cmake linux-headers python3 git libstdc++
    - pip3 install conan
  script:
    - mkdir build
    - cd build
    - conan install --build -scompiler.libcxx=libstdc++11 ..
    - cmake ..
    - cmake --build . -- -j
  variables:
    GIT_SUBMODULE_STRATEGY: normal
  artifacts:
    paths:
      - 'build/bin/unit_tests'

unittests:
  stage: test
  script:
    - ./build/bin/unit_tests
